server:
  port: 8080
spring:
  application:
    name: gateway
  profiles:
    active: dev
zuul:
  routes:
    api-index:
      path: /api/index/**
      serviceId: index 
    api-comment:
      path: /api/comment/**
      serviceId: comment 
    api-sys:
      path: /api/sys/**
      serviceId: antd-sys
      strip-prefix: false
    api-article:
      path: /api/article/**
      serviceId: article 
  host:
    connect-timeout-millis: 60000
    socket-timeout-millis: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
